server: 
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_database:3306/pepperfry
    username: root
    password: welcome3
    
  jpa:
    show-sql: true
    generate-ddl: true
 